Create dependency-management.md
dotnet/source-build pull request #3403
Opened 2023-04-20 19:59 UTC by ViktorHofer

Drafted on 4/20/2023 by @mmitche, @MichaelSimons, @mthalman and @ViktorHofer

2023-04-25 14:57 UTC, mmitche commented on Documentation/dependency-management.md
> +| **Dependency Source** | **Description** | **Requirements** | **Configurations** |
Good idea.

2023-06-10 11:16 UTC, Gitter470 requested changes
Documentation/dependency-management.md

2023-06-30 18:39 UTC, mthalman commented on Documentation/dependency-management.md
> +| [Source Build Externals (SBE)](https://github.com/dotnet/source-build-externals) | The source-build-externals repo contains the source of external .NET dependencies. The repository wraps and builds
```suggestion
| [Source Build Externals (SBE)](https://github.com/dotnet/source-build-externals) | The source-build-externals repo contains the source of external .NET dependencies. The repository wraps and builds them according to source-build requirements. | <ul><li>Repository producing dependency is not on arcade</li><li>Dependency should not update often</li><li>Dependency outputs one or more NuGet packages</li></ul> | Source-Build |
```

2023-06-30 18:39 UTC, mthalman commented on Documentation/dependency-management.md
> +| [Source Build Reference Packages (SBRP)](https://github.com/dotnet/source-build-reference-packages) | The source-build-reference packages repo contains source for the surface area of released .NET
```suggestion
| [Source Build Reference Packages (SBRP)](https://github.com/dotnet/source-build-reference-packages) | The source-build-reference packages repo contains source for the surface area of previously released .NET packages. | <ul><li>Dependency is contract-only. Not executed</li><li>Should not update often</li><li>Dependency is stable and released</li><li>Not already included in source-build-externals.</li><li>Package should be produced by .NET.</li><li>NuGet package.</li></ul> | Source-Build |
```

2023-06-30 18:39 UTC, mthalman commented on Documentation/dependency-management.md
> +| Previously source-built packages | As input to source-build, a set of previously source built packages are supplied, generated from the previous release or Microsoft's own release in certain bootst
```suggestion
| Previously source-built packages | As input to source-build, a set of previously source built packages are supplied, generated from the previous release or Microsoft's own release in certain bootstrapping scenarios. The versions of these inputs flow into the build, overriding elements in eng/Versions.props. | <ul><li>Input must be part of the previously source built product.</li><li>Input package must provide a compatible surface area.</li><li>Contents of package may not be redistributed into a shipping product asset (AKA [poisoning](leak-detection.md)).</li></ul> | Source-Build |
```

2023-10-09 09:07 UTC, ViktorHofer commented
@MichaelSimons can you please help take this work over and drive it to completion? Merely asking as this PR is showing up on my open Pull Requests list.

2023-11-13 11:23 UTC, closed without merging